[project]
name = "price-prediction"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "category-encoders>=2.10.0",
    "joblib>=1.6.0",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
    "streamlit>=1.62.0",
]

[project.scripts]
price-prediction = "price_prediction:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
